- name: configure backend server 
  become: yes
  hosts: backend
  tasks:
    - name: disable default node js
      ansible.builtin.command: dnf module disable nodejs -y
    
    - name: enable node js
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs 
      ansible.builtin.dnf: 
        name: nodejs
        state: installed 





