- name: configure DB server 
  hosts: web 
  become: yes
  tasks:
  - name: install mysql 
    ansible.builtin.dnf:
    state: latest 
  - name:  start and enable MySQL server 
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes


